---
title: "zanedbání povinné výživy"
author: "Václav Haisman"
date: "červenec 2016"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    latex_engine: lualatex
    toc: yes
    includes:
      in_header: header.tex
  html_document: default
  word_document: default
mainfont: Charis SIL
lang: cs-CZ
geometry: a4paper
---

```{r, echo=FALSE, message=FALSE}
library(knitr)
#library(sqldf)
library(tcltk)
library(gsubfn)
library(proto)
#library(RSQLite)
#library(DBI)
library(ggplot2)
#library(ppls)
#library(TTR)
#library(forecast)
library(clusterSim)
#library(reshape2)
#library(Jmisc)
library(pander)
#library(xtable)
#options(xtable.floating=FALSE)
options("scipen"=100, "digits"=10)
```

# Zanedbání povinné výživy v České Republice

## Zdroje dat

- nezaměstnanost podle ČSÚ: <https://vdb.czso.cz/vdbvo2/faces/index.jsf?page=vystup-objekt&pvo=ZAM06&z=T&f=TABULKA&katalog=30853&str=v95&c=v3~8__RP2015>

- statistiky trestných činů zanedbání povinné výživy:
    - do roku 2007: <http://www.policie.cz/clanek/archiv-statistiky-statisticke-prehledy-kriminality.aspx>
    - rok 2008: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2008.aspx>
    - rok 2009: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2009.aspx>
    - rok 2010: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2010.aspx>
    - rok 2011: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2011.aspx>
    - rok 2012: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2012.aspx>
    - rok 2013: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2013.aspx>
    - rok 2014: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2014.aspx>
    - rok 2015: <http://www.policie.cz/clanek/statisticke-prehledy-kriminality-za-rok-2015.aspx>

- statistiky nezaměstnanosti podle MPSV: <https://portal.mpsv.cz/sz/stat/stro>

## Data

```{r, echo=FALSE, message=FALSE}
readCsv <- function(fileName) {
  DF <- read.csv2(fileName, fileEncoding = "UTF-8",
                  sep = ",", quote = "\"", header = TRUE, dec = ",", na.strings = c("neznámo"))
  return(DF)
}

printTable <- function(dataFrame) {
  kable(dataFrame, digits = 2,
        format.args = list(big.mark = ' ', decimal.mark = ","),
        row.names = FALSE)
}

printTable2 <- function(dataFrame) {
    pander(dataFrame, digits = 2, decimal.mark = ",", big.mark = ' ',
           keep.trailing.zeroes = TRUE,
           table.split.cells = 15)
}

printTableSmall <- function(dataFrame) {
    pander(dataFrame, digits = 2, decimal.mark = ",", big.mark = ' ',
           keep.trailing.zeroes = TRUE, 
           graph.fontsize=10)
}

fmtNum <- function(x) {
    format(x, digits=2, decimal.mark = ",")
}

fmtNumM <- function(x) {
    format(x, digits=2, decimal.mark = "{,}")
}

fmtNum2 <- function(x, digits) {
    format(x, digits=digits, decimal.mark = ",")
}

```

```{r, echo=FALSE}
tblColNames <- c("rok", "zjištěno", "stíháno osob", "z toho ženy", "paragraf", "nezaměstnanost v % (ČSÚ)", "HDP (výrobní metodou) v mil. Kč", "nezaměstnanost v % (MPSV)", "počet evidovaných uchazečů (průměr, MPSV)", "nově hlášených 1.-12. (MPSV)")

DF <- readCsv("zanedbání-povinné-výživy-statistika.csv")

printTable2(setNames(DF, tblColNames))
```

## Normalizovaná data

```{r, echo=FALSE, fig.cap="Normalizovaná data"}
pdf.options(encoding = 'CP1250')

nDF <- data.frame(
    rok=DF$rok,
    zjistenych=data.Normalization(DF$zjistenych, type="n4"),
    pocEvid=data.Normalization(DF$pocEvid, type="n4"))

printTable2(nDF)
```

```{r, echo=FALSE, fig.keep="high", fig.cap="Graf normalizovaných hodnot zjištěných trestných činů zanedbání povinné výživy a počtu evidovaných nezaměstnaných (MPSV ČR)."}
pdf.options(encoding = 'CP1250')

a <- data.frame(rok = nDF$rok, id = factor(rep("průměrný počet evidovaných\nnezaměstnaných za rok", each = length(nDF$rok))), value = nDF$pocEvid)
b <- data.frame(rok = nDF$rok, id = factor(rep("zjištěných trestných činů\nzanedbání povinné výživy", each = length(nDF$rok))), value = nDF$zjistenych)
nDF2 <- do.call(rbind, list(a,b))

ggplot(nDF2, aes(x=factor(rok), y = value, group=id, color=id)) +
    geom_point() +
    geom_line() +
    labs(color = "řady", x = "rok", y = "[-]") +
    theme(legend.position="top")

```

```{r, echo=FALSE, fig.keep="high", fig.cap="Korelacezjištěných trestných činů zanedbání povinné výživy a počtu evidovaných nezaměstnaných (MPSV ČR)"}
pdf.options(encoding = 'CP1250')

ggplot(DF,aes(pocEvid, zjistenych)) +
    geom_point() +
    stat_smooth(formula = y ~ x, method="gam", level=0.99) +
    geom_text(aes(label=rok), hjust=0.25, vjust=-0.25, angle=45, check_overlap = FALSE) +
    scale_x_continuous(breaks = seq(round(min(DF$pocEvid), -5), round(max(DF$pocEvid), -5), by = 50000)) +
    labs(x = "průměrný počet evidovaných nezaměstnaných za rok",
         y = "zjištěných trestných činů zanedbání povinné výživy")
```

```{r, echo=FALSE}
CorrTest <- cor.test(DF$zjistenych, DF$pocEvid, conf.level = 0.99, method = "pearson")
Corr <- CorrTest$estimate

CorrTestS <- cor.test(DF$zjistenych, DF$pocEvid, conf.level = 0.99, method = "spearman")
CorrS <- CorrTestS$estimate
```





